---
title: Contentz
description: Create Content, Get a Highly Optimized Website
domain: https://contentz.tech
repository: https://github.com/sergiodxa/contentz-website
social:
  github: sergiodxa/contentz
navigation:
  - name: Documentation
    path: /docs/
  - name: Code
    path: https://github.com/sergiodxa/contentz
incremental: false
language: en
